"""Generating basic structure

Revision ID: 240e7df557fc
Revises: 
Create Date: 2023-01-30 19:36:37.956077

"""
import os

import sqlalchemy as sa
from dotenv import load_dotenv
from sqlalchemy.schema import CreateSequence, Sequence

from alembic import op

load_dotenv()

# revision identifiers, used by Alembic.
revision = "240e7df557fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"create schema if not exists {os.getenv('SCHEMA')}")
    op.execute(CreateSequence(Sequence("network_coverage_seq")))

    op.create_table(
        "city",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "operator",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "network_coverage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("operator", sa.String(length=50), nullable=True),
        sa.Column("2G", sa.Boolean(), nullable=True),
        sa.Column("3G", sa.Boolean(), nullable=True),
        sa.Column("4G", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city"],
            ["city.name"],
        ),
        sa.ForeignKeyConstraint(
            ["operator"],
            ["operator.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city", "operator", "2G", "3G", "4G"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("network_coverage")
    op.drop_table("operator")
    op.drop_table("city")
    # ### end Alembic commands ###
