"""init db with basic structure

Revision ID: 560ee29cbb84
Revises: 
Create Date: 2023-01-29 17:28:26.048752

"""
import os

from alembic import op
import sqlalchemy as sa

from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision = '560ee29cbb84'
down_revision = None
branch_labels = None
depends_on = None
schema = os.getenv("SCHEMA")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"create schema if not exists {schema}")

    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator')
    op.drop_table('network')
    op.drop_table('city')
    # ### end Alembic commands ###
