"""Add sequences

Revision ID: 9bbe8ec0ae31
Revises: 65aac47342a1
Create Date: 2023-01-30 00:45:15.730265

"""
from alembic import op
from sqlalchemy.schema import CreateSequence, Sequence



# revision identifiers, used by Alembic.
revision = '9bbe8ec0ae31'
down_revision = '65aac47342a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(CreateSequence(Sequence("operator_seq")))
    op.execute(CreateSequence(Sequence("network_seq")))
    op.execute(CreateSequence(Sequence("city_seq")))
    op.execute(CreateSequence(Sequence("network_coverage_seq")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
