version: "3.8"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=papernest
      - POSTGRES_PASSWORD=papernest
      - POSTGRES_DB=papernest
    expose:
      - "54320"
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - "8000"
    ports:
      - "8000:8000"
