version: "3.8"
services:
  db:
    image: "postgres"
    container_name: "papernest_db"
    environment:
      - POSTGRES_USER=papernest
      - POSTGRES_PASSWORD=papernest
      - POSTGRES_DB=papernest
    expose:
      - "54320"
    ports:
      - "54320:5432"
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      - alembic upgrade head
      -
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - "8000"
    ports:
      - "8000:8000"
